version: "3.8"

services:
  pipelines:
    image: "pipelines"
    ports:
      - "8686:8686"
    volumes:
      - "./conf:/usr/local/pipelines/conf"
    secrets:
      - blob_secret
    depends_on:
      minio:
        condition: service_healthy
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${NBALAKE_KEY}
      - MINIO_ROOT_PASSWORD=${NBALAKE_SECRET}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    healthcheck:
      start_period: 5s
      test: "timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
secrets:
  blob_secret:
    file: ./conf/config.json
volumes:
  data:
  conf:
